from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import typer
from rich.prompt import Confirm
from rich.table import Table

from raincurve.config import load_global_config
from raincurve.remote.connection import RemoteHost
from raincurve.remote import provisioner
from raincurve.ui.console import console, rc_error, rc_print, rc_success, rc_warn

remote_app = typer.Typer(
    name="remote",
    help="Run sandboxes on remote machines over SSH.",
    no_args_is_help=True,
)


def _parse_agent_result(output_lines: list[str]) -> dict | None:
    full_output = "\n".join(output_lines)
    for line in reversed(output_lines):
        line = line.strip()
        if line.startswith("{"):
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                pass
    try:
        json_start = full_output.rfind("{")
        json_end = full_output.rfind("}") + 1
        if json_start >= 0 and json_end > json_start:
            return json.loads(full_output[json_start:json_end])
    except json.JSONDecodeError:
        pass
    return None


def _build_coding_agent_prompt(issue: str, result: dict | None, raw_output: str) -> str:
    lines = [
        "# Bug Fix Request",
        "",
        "## Issue",
        issue,
        "",
    ]

    if result and result.get("success"):
        summary = result.get("summary", "")
        findings = result.get("findings", [])

        if summary:
            lines.extend(["## Root Cause Analysis", summary, ""])

        if findings:
            lines.append("## Findings")
            for i, f in enumerate(findings, 1):
                lines.append(
                    f"\n### {i}. [{f.get('severity', '?').upper()}] {f.get('title', 'Untitled')}"
                )
                if f.get("endpoint"):
                    lines.append(f"- **Code path:** {f['endpoint']}")
                if f.get("evidence"):
                    lines.append(f"- **Evidence:** {f['evidence']}")
            lines.append("")

        lines.extend(
            [
                "## Instructions",
                "Fix this bug. The analysis above was generated by an automated agent that:",
                "- Read the source code and traced the logic",
                "- Queried the database to verify data state",
                "- Triggered the bug and observed actual vs expected output",
                "",
                "Apply the minimal fix needed. Do not refactor unrelated code.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Agent Output (raw)",
                "The automated investigation could not produce structured findings.",
                "Raw output from the investigation:",
                "",
                "```",
                raw_output[-3000:] if len(raw_output) > 3000 else raw_output,
                "```",
                "",
                "## Instructions",
                "Investigate and fix the issue described above using the agent's raw output as context.",
                "",
            ]
        )

    return "\n".join(lines)


def _resolve_host(
    host: str | None,
    key: str | None,
    port: int,
) -> RemoteHost | None:
    if host:
        return RemoteHost.from_string(host, key_path=key, port=port)
    saved = provisioner.load_remote_config()
    if saved:
        if key:
            saved.key_path = key
        return saved
    rc_error("No host specified.", hint="Use --host user@ip or run `raincurve remote setup` first.")
    return None


def _ensure_provisioned(conn: RemoteHost) -> bool:
    """Make sure the remote has Docker, raincurve, and LLM configured. Auto-installs if missing."""
    r = conn.test()
    if not r.ok:
        rc_error(f"SSH failed: {r.stderr}")
        return False

    checks = provisioner.check_prerequisites(conn)

    # Docker
    if not checks.get("docker"):
        rc_print("  Docker not found on remote — installing...")
        r = provisioner.install_docker(conn)
        if not r.ok:
            rc_error(f"Docker install failed: {r.stderr}")
            return False
        rc_success("Docker installed")

    # Raincurve
    rc_check = conn.run("export PATH=$HOME/.local/bin:$PATH && raincurve --version 2>/dev/null")
    if not rc_check.ok or "raincurve" not in rc_check.stdout.lower():
        rc_print("  raincurve not found on remote — installing...")
        r = provisioner.install_raincurve(conn)
        if not r.ok:
            rc_warn(f"raincurve install may have issues: {r.stdout[-200:]}")
        else:
            rc_success("raincurve installed")

    # LLM config
    llm_check = conn.run("cat ~/.raincurve/global.json 2>/dev/null")
    if not llm_check.ok or '"api_key"' not in llm_check.stdout:
        cfg = load_global_config()
        provider = cfg.llm.provider or "openrouter"
        api_key = cfg.llm.api_key or cfg.llm.openrouter_api_key or ""
        if api_key:
            rc_print(f"  Configuring LLM ({provider}) on remote...")
            provisioner.configure_llm(conn, provider, api_key)
            rc_success("LLM configured")
        else:
            rc_error("No LLM API key found.", hint="Run `raincurve init` first.")
            return False

    provisioner.save_remote_config(conn)
    return True


def _run_sandbox(
    conn: RemoteHost,
    repo: str,
    env_file: str | None,
    env: list[str],
    json_output: bool,
    yes: bool,
) -> bool:
    """Clone repo, upload env, run sandbox on remote. Returns True on success."""

    # 1. Clone repo
    rc_print("  Cloning repository...")
    ok, remote_dir = provisioner.clone_repo(conn, repo)
    if not ok:
        rc_error(f"Clone failed: {remote_dir}")
        return False
    rc_success(f"Repo at {remote_dir}")

    # 2. Upload env file / vars
    env_vars: dict[str, str] = {}
    if env_file:
        local = Path(env_file)
        if not local.exists():
            rc_error(f"Env file not found: {env_file}")
            return False
        rc_print("  Uploading environment file...")
        r = provisioner.upload_env_file(conn, str(local), remote_dir)
        if not r.ok:
            rc_error(f"Upload failed: {r.stderr}")
            return False
        rc_success("Environment file uploaded")
        for line in local.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env_vars[k.strip()] = v.strip()

    for e in env:
        if "=" in e:
            k, v = e.split("=", 1)
            env_vars[k] = v

    if env_vars and not env_file:
        provisioner.upload_env_vars(conn, env_vars, remote_dir)

    # 3. Quick remote analysis
    rc_print("  Analyzing project...")
    conn.run(
        f"cd {remote_dir} && "
        "echo '=== FILES ===' && ls -1 && "
        "echo '=== PACKAGE ===' && "
        "(cat package.json 2>/dev/null | head -30 || "
        "cat requirements.txt 2>/dev/null | head -20 || "
        "cat Pipfile 2>/dev/null | head -20 || "
        "cat go.mod 2>/dev/null | head -10 || "
        "cat Gemfile 2>/dev/null | head -20 || "
        "echo 'No package file found') && "
        "echo '=== DOCKER ===' && "
        "(cat Dockerfile 2>/dev/null | head -5 || echo 'No Dockerfile') && "
        "echo '=== ENV ===' && "
        "(cat .env 2>/dev/null | grep -v '^#' | cut -d= -f1 | head -20 || echo 'No .env')"
    )

    # 4. Approval
    if not yes:
        console.print()
        rc_print("[bold]Sandbox Plan:[/bold]")
        console.print()
        rc_print(f"  Repository:  {repo}")
        rc_print(f"  Remote dir:  {remote_dir}")
        rc_print(f"  Host:        {conn.label}")
        if env_vars:
            rc_print(f"  Env vars:    {len(env_vars)} variables")
            for k in list(env_vars.keys())[:8]:
                is_secret = any(s in k.lower() for s in ["key", "secret", "password", "token"])
                val = "****" if is_secret else env_vars[k][:30]
                rc_print(f"               {k}={val}", style="rc.dim")
            if len(env_vars) > 8:
                rc_print(f"               ... and {len(env_vars) - 8} more", style="rc.dim")
        console.print()

        rc_print("[bold]Raincurve will:[/bold]")
        rc_print("  1. Analyze the codebase (detect stack, DBs, external deps)")
        rc_print("  2. Spin up infrastructure (databases, caches, API mocks)")
        rc_print("  3. Build and run the application in Docker")
        rc_print("  4. Seed realistic test data")
        rc_print("  5. Run end-to-end smoke tests")
        console.print()

        if not Confirm.ask("  Proceed?", default=True):
            rc_print("  Cancelled.\n")
            return False

    console.print()
    rc_print("  Starting sandbox (this takes several minutes)...")
    rc_print("  Streaming output from remote:\n", style="rc.dim")
    console.print("  " + "─" * 60)

    # 5. Run sandbox on remote
    sandbox_cmd = f"cd {remote_dir} && export PATH=$HOME/.local/bin:$PATH && raincurve sandbox -y"
    if json_output:
        sandbox_cmd += " --json"

    exit_code = conn.run_stream(
        sandbox_cmd,
        on_line=lambda line: console.print(f"  {line}"),
        timeout=900,
    )

    console.print("  " + "─" * 60)
    console.print()

    provisioner.save_active_project(remote_dir)
    return exit_code == 0


# --------------------------------------------------------------------------- #
#  setup
# --------------------------------------------------------------------------- #
@remote_app.command()
def setup(
    host: str = typer.Argument(..., help="SSH connection string (user@host or user@host:port)"),
    key: str = typer.Option(None, "--key", "-k", help="Path to SSH private key"),
    port: int = typer.Option(22, "--port", "-p", help="SSH port"),
) -> None:
    """Connect to a remote machine, verify Docker, and install raincurve."""
    conn = RemoteHost.from_string(host, key_path=key, port=port)
    console.print(f"\n  [bold]Remote setup:[/bold] {conn.label}\n")

    # 1. SSH connectivity
    rc_print("  Testing SSH connection...")
    r = conn.test()
    if not r.ok:
        rc_error(f"SSH failed: {r.stderr}")
        rc_print("  Check your host, username, key, and port.", style="rc.dim")
        return
    rc_success("SSH connected")

    # 2. Prerequisites
    rc_print("  Checking prerequisites...")
    checks = provisioner.check_prerequisites(conn)

    table = Table(show_header=False, padding=(0, 2))
    table.add_column("Check", style="bold", width=20)
    table.add_column("Status")

    docker_ok = checks.get("docker", False)
    git_ok = checks.get("git", False)
    disk = checks.get("disk_gb", 0)
    ram = checks.get("ram_gb", 0)

    table.add_row(
        "Docker",
        f"[green]v{checks.get('docker_version', '?')}[/]" if docker_ok else "[red]Not found[/]",
    )
    table.add_row("Git", "[green]Available[/]" if git_ok else "[red]Not found[/]")
    table.add_row(
        "Disk",
        f"[green]{disk:.0f} GB free[/]"
        if disk >= 10
        else f"[yellow]{disk:.0f} GB free (need 10+)[/]",
    )
    table.add_row(
        "RAM", f"[green]{ram} GB[/]" if ram >= 4 else f"[yellow]{ram} GB (recommend 4+)[/]"
    )
    console.print(table)

    # 3. Install Docker if missing
    if not docker_ok:
        if Confirm.ask("\n  Docker not found. Install it?", default=True):
            rc_print("  Installing Docker (this takes a minute)...")
            r = provisioner.install_docker(conn)
            if r.ok:
                rc_success("Docker installed")
            else:
                rc_error(f"Docker install failed: {r.stderr}")
                return
        else:
            rc_error("Docker is required. Setup cannot continue.")
            return

    # 4. Install raincurve
    rc_print("  Installing raincurve on remote...")
    r = provisioner.install_raincurve(conn)
    if r.ok and "raincurve" in r.stdout.lower():
        rc_success(f"raincurve installed ({r.stdout.splitlines()[-1].strip()})")
    else:
        rc_warn(f"raincurve install may have issues: {r.stdout[-200:]}")
        rc_print("  Continuing anyway — the sandbox command will verify.", style="rc.dim")

    # 5. Configure LLM on remote
    cfg = load_global_config()
    provider = cfg.llm.provider or "openrouter"
    api_key = cfg.llm.api_key or cfg.llm.openrouter_api_key or ""

    if api_key:
        rc_print(f"  Configuring LLM ({provider}) on remote...")
        r = provisioner.configure_llm(conn, provider, api_key)
        if r.ok:
            rc_success("LLM configured on remote")
        else:
            rc_warn(f"LLM config issue: {r.stderr}")
    else:
        rc_warn("No LLM API key found locally. Run `raincurve init` first, then re-run setup.")

    # 6. Save remote config
    provisioner.save_remote_config(conn)
    rc_success("Remote host saved as default")

    console.print()
    rc_success("Setup complete!")
    rc_print(
        "  Next: raincurve remote sandbox <repo-url> --env-file .env\n",
        style="rc.dim",
    )


# --------------------------------------------------------------------------- #
#  sandbox
# --------------------------------------------------------------------------- #
@remote_app.command()
def sandbox(
    repo: str = typer.Argument(..., help="Git repository URL to clone and sandbox"),
    host: str = typer.Option(
        None, "--host", "-H", help="SSH connection (user@host). Uses saved default if omitted."
    ),
    env_file: str = typer.Option(None, "--env-file", "-e", help="Local .env file to upload"),
    env: list[str] = typer.Option([], "--env", help="Environment variable (KEY=VALUE), repeatable"),
    key: str = typer.Option(None, "--key", "-k", help="Path to SSH private key"),
    port: int = typer.Option(22, "--port", "-p", help="SSH port"),
    json_output: bool = typer.Option(False, "--json", help="Output structured JSON"),
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip approval prompt"),
) -> None:
    """Clone a repo on a remote machine and spin up a production sandbox."""
    conn = _resolve_host(host, key, port)
    if not conn:
        return

    console.print("\n  [bold]Remote sandbox[/bold]")
    rc_print(f"  Host: {conn.label}", style="rc.dim")
    rc_print(f"  Repo: {repo}", style="rc.dim")
    console.print()

    # Auto-provision if the remote isn't ready
    rc_print("  Checking remote environment...")
    if not _ensure_provisioned(conn):
        return
    rc_success("Remote environment ready")

    # Run the sandbox
    ok = _run_sandbox(conn, repo, env_file, env, json_output, yes)

    if json_output:
        remote_dir = provisioner.load_active_project()
        if remote_dir:
            r = conn.run(f"cat {remote_dir}/.raincurve/run_state.json 2>/dev/null")
            if r.ok:
                print(r.stdout)
    else:
        if ok:
            rc_success("Remote sandbox is running!")
            console.print()
            rc_print("  To reproduce issues:")
            rc_print(
                '  raincurve remote reproduce "describe the bug here"',
                style="rc.dim",
            )
            rc_print("\n  To tear down:")
            rc_print("  raincurve remote teardown", style="rc.dim")
        else:
            rc_error("Sandbox failed — check the output above.")
            remote_dir = provisioner.load_active_project()
            if remote_dir and not json_output:
                console.print()
                if Confirm.ask("  Drop into interactive chat to guide the agent?", default=True):
                    rc_print("  Starting interactive session (Ctrl+C to exit)...\n")
                    chat_cmd = (
                        f"cd {remote_dir} && export PATH=$HOME/.local/bin:$PATH && raincurve chat"
                    )
                    conn.run_interactive(chat_cmd)

    console.print()


# --------------------------------------------------------------------------- #
#  reproduce
# --------------------------------------------------------------------------- #
@remote_app.command()
def reproduce(
    description: str = typer.Argument(..., help="Bug description — what to reproduce"),
    host: str = typer.Option(
        None, "--host", "-H", help="SSH connection. Uses saved default if omitted."
    ),
    repo: str = typer.Option(
        None, "--repo", "-r", help="Git repo URL — auto-provisions sandbox if not running."
    ),
    env_file: str = typer.Option(
        None, "--env-file", "-e", help="Local .env file (used if auto-provisioning)."
    ),
    env: list[str] = typer.Option(
        [], "--env", help="Environment variable KEY=VALUE (used if auto-provisioning), repeatable."
    ),
    project: str = typer.Option(
        None, "--project", help="Remote project directory. Uses last sandbox if omitted."
    ),
    key: str = typer.Option(None, "--key", "-k", help="Path to SSH private key"),
    port: int = typer.Option(22, "--port", "-p", help="SSH port"),
    json_output: bool = typer.Option(False, "--json", help="Output structured JSON"),
) -> None:
    """Reproduce a bug in the running remote sandbox and generate a report."""
    conn = _resolve_host(host, key, port)
    if not conn:
        return

    remote_dir = project or provisioner.load_active_project()

    console.print("\n  [bold]Remote reproduce[/bold]")
    rc_print(f"  Host: {conn.label}", style="rc.dim")
    rc_print(f"  Issue: {description[:100]}", style="rc.dim")
    console.print()

    # Auto-provision + auto-sandbox if nothing is running
    rc_print("  Checking sandbox status...")
    sandbox_running = False
    if remote_dir:
        status = provisioner.get_sandbox_status(conn, remote_dir)
        sandbox_running = status is not None

    if not sandbox_running:
        if not repo:
            rc_error(
                "No running sandbox and no --repo provided.",
                hint="Use --repo <url> to auto-provision, or run `raincurve remote sandbox` first.",
            )
            return

        rc_warn("No sandbox running — provisioning automatically...")
        console.print()

        if not _ensure_provisioned(conn):
            return

        ok = _run_sandbox(conn, repo, env_file, env, json_output=False, yes=False)
        if not ok:
            rc_error("Sandbox provisioning failed — cannot reproduce.")
            return

        remote_dir = provisioner.load_active_project()
        if not remote_dir:
            rc_error("Could not determine remote project directory after provisioning.")
            return

        rc_success("Sandbox provisioned — now reproducing the issue...")
        console.print()
    else:
        rc_success("Sandbox is running")
        rc_print(f"  Project: {remote_dir}", style="rc.dim")

    # Build the reproduce prompt — deep investigation, not just endpoint probing
    prompt = (
        f"ISSUE TO INVESTIGATE:\n{description}\n\n"
        "You are investigating a bug in a live application. Do NOT just hit API endpoints "
        "and look for HTTP errors. Many bugs are data correctness issues — wrong values, "
        "missing records, incorrect calculations, logic errors that return 200 OK with bad data.\n\n"
        "INVESTIGATION PROCESS:\n"
        "1. READ THE CODE FIRST. Use bash to grep and cat the source files. Find the code "
        "path that handles the described behavior. Identify the relevant files, functions, "
        "and database queries.\n"
        "2. QUERY THE DATABASE. Use the database CLI tools available in the containers "
        "(psql, mysql, mongosh, etc.) to inspect the actual data. Run the same queries the "
        "code runs and check if the results are correct.\n"
        "3. CHECK APPLICATION LOGS. Read container logs with docker logs. Look for warnings, "
        "errors, or unexpected values.\n"
        "4. TRIGGER THE BUG. Hit the relevant endpoints or run the relevant code paths with "
        "inputs that should trigger the issue. Compare actual output vs expected output.\n"
        "5. TRACE THE ROOT CAUSE. Follow the code from input to output. Find the exact "
        "file and function where the logic breaks. Note the line numbers.\n"
        "6. DOCUMENT EVERYTHING for a coding agent to fix it.\n\n"
        "In your findings, you MUST include:\n"
        "- title: what the bug is\n"
        "- severity: critical/high/medium/low\n"
        "- evidence: the actual vs expected output you observed\n"
        "- endpoint: the API route or code path affected\n\n"
        "In your summary, include ALL of the following so a coding agent can fix this "
        "without any additional context:\n"
        "- ROOT CAUSE: exact file path(s) and function name(s) where the bug lives\n"
        "- REPRODUCTION: the exact commands (curl, psql, etc.) that trigger the bug\n"
        "- EXPECTED vs ACTUAL: what the output should be vs what it is\n"
        "- SUGGESTED FIX: what specifically needs to change in the code\n"
    )

    # Run chat agent on remote
    escaped_prompt = prompt.replace("'", "'\\''")
    chat_cmd = (
        f"cd {remote_dir} && "
        "export PATH=$HOME/.local/bin:$PATH && "
        f"raincurve chat --json '{escaped_prompt}'"
    )

    console.print()
    rc_print("  Investigating issue (this may take several minutes)...")
    rc_print("  Agent is reading code, querying databases, tracing logic...\n", style="rc.dim")
    console.print("  " + "─" * 60)

    output_lines: list[str] = []
    conn.run_stream(
        chat_cmd,
        on_line=lambda line: (output_lines.append(line), console.print(f"  {line}")),
        timeout=600,
    )

    console.print("  " + "─" * 60)
    console.print()

    # Parse JSON result from output
    result = _parse_agent_result(output_lines)
    full_output = "\n".join(output_lines)

    # Build the coding agent prompt
    coding_prompt = _build_coding_agent_prompt(description, result, full_output)

    # Save report
    reports_dir = Path.home() / ".raincurve" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%S")

    report_data = {
        "host": conn.label,
        "project": remote_dir,
        "issue": description,
        "timestamp": ts,
        **(result or {}),
        "coding_agent_prompt": coding_prompt,
    }

    report_path = reports_dir / f"reproduce-{ts}.json"
    report_path.write_text(json.dumps(report_data, indent=2), encoding="utf-8")

    prompt_path = reports_dir / f"reproduce-{ts}.prompt.md"
    prompt_path.write_text(coding_prompt, encoding="utf-8")

    if json_output:
        print(json.dumps(report_data, indent=2))
        return

    # Display results
    if result and result.get("success"):
        verdict = result.get("verdict", "unknown")
        summary = result.get("summary", "")
        findings = result.get("findings", [])

        verdict_style = {
            "succeeded": "rc.success",
            "found_issue": "rc.warn",
            "stuck": "rc.warn",
            "errored": "rc.error",
        }.get(verdict, "rc.info")

        rc_print(f"  Verdict: [{verdict_style}]{verdict}[/{verdict_style}]")
        console.print()

        if summary:
            rc_print("[bold]  Analysis:[/bold]")
            for line in summary.split("\n"):
                rc_print(f"    {line}")
            console.print()

        if findings:
            rc_print("[bold]  Findings:[/bold]")
            for f in findings:
                sev = f.get("severity", "?")
                title = f.get("title", "?")
                evidence = f.get("evidence", "")
                endpoint = f.get("endpoint", "")

                sev_style = {
                    "critical": "red bold",
                    "high": "red",
                    "medium": "yellow",
                    "low": "cyan",
                }.get(sev, "white")

                rc_print(f"    [{sev_style}][{sev}][/{sev_style}] {title}")
                if endpoint:
                    rc_print(f"          Path: {endpoint}", style="rc.dim")
                if evidence:
                    for eline in evidence.split("\n")[:5]:
                        rc_print(f"          {eline[:200]}", style="rc.dim")
            console.print()

        duration = result.get("duration_s", 0)
        tools = result.get("tool_calls", 0)
        rc_print(f"  Duration: {duration:.1f}s | Tool calls: {tools}", style="rc.dim")
    else:
        rc_warn("Could not parse structured results from agent.")
        rc_print("  See the raw output above.", style="rc.dim")

    console.print()
    rc_print(f"  Report: {report_path}", style="rc.dim")
    rc_success(f"Coding agent prompt: {prompt_path}")
    rc_print("  Paste the .prompt.md file into Claude or Cursor to get a fix.\n", style="rc.dim")


# --------------------------------------------------------------------------- #
#  status
# --------------------------------------------------------------------------- #
@remote_app.command()
def status(
    host: str = typer.Option(
        None, "--host", "-H", help="SSH connection. Uses saved default if omitted."
    ),
    project: str = typer.Option(None, "--project", help="Remote project directory"),
    key: str = typer.Option(None, "--key", "-k", help="Path to SSH private key"),
    port: int = typer.Option(22, "--port", "-p", help="SSH port"),
) -> None:
    """Check the status of a remote sandbox."""
    conn = _resolve_host(host, key, port)
    if not conn:
        return

    remote_dir = project or provisioner.load_active_project()
    if not remote_dir:
        rc_error("No active remote project.", hint="Use --project or run sandbox first.")
        return

    console.print(f"\n  [bold]Remote status[/bold] — {conn.label}\n")

    r = conn.test()
    if not r.ok:
        rc_error(f"SSH failed: {r.stderr}")
        return

    state = provisioner.get_sandbox_status(conn, remote_dir)
    if not state:
        rc_warn("No running sandbox found.")
        console.print()
        return

    rc_print(f"  Project: {remote_dir}")
    rc_print(f"  Network: {state.get('network_name', '?')}")

    containers = state.get("containers", {})
    if containers:
        console.print()
        table = Table(show_header=True, header_style="bold cyan", padding=(0, 2))
        table.add_column("Service")
        table.add_column("Container")
        table.add_column("Port")
        table.add_column("Status")

        for name, info in containers.items():
            port_val = str(info.get("host_port", "-")) if info.get("host_port") else "-"
            table.add_row(
                name, info.get("container_id", "?")[:12], port_val, info.get("status", "?")
            )
        console.print(table)

    # Check if containers are actually running
    r = conn.run(
        "docker ps --format '{{.Names}} {{.Status}}' --filter 'label=rc-aux-of' 2>/dev/null | head -20"
    )
    if r.ok and r.stdout:
        console.print()
        rc_print("  Live containers:")
        for line in r.stdout.splitlines():
            rc_print(f"    {line}", style="rc.dim")

    console.print()


# --------------------------------------------------------------------------- #
#  chat
# --------------------------------------------------------------------------- #
@remote_app.command()
def chat(
    host: str = typer.Option(
        None, "--host", "-H", help="SSH connection. Uses saved default if omitted."
    ),
    project: str = typer.Option(None, "--project", help="Remote project directory"),
    key: str = typer.Option(None, "--key", "-k", help="Path to SSH private key"),
    port: int = typer.Option(22, "--port", "-p", help="SSH port"),
) -> None:
    """Interactive chat with the remote sandbox — guide the agent in real time."""
    conn = _resolve_host(host, key, port)
    if not conn:
        return

    remote_dir = project or provisioner.load_active_project()
    if not remote_dir:
        rc_error("No active remote project.", hint="Run sandbox first or use --project.")
        return

    console.print(f"\n  [bold]Remote chat[/bold] — {conn.label}")
    rc_print(f"  Project: {remote_dir}", style="rc.dim")
    rc_print("  Starting interactive session (Ctrl+C to exit)...\n")

    chat_cmd = f"cd {remote_dir} && export PATH=$HOME/.local/bin:$PATH && raincurve chat"
    conn.run_interactive(chat_cmd)
    console.print()


# --------------------------------------------------------------------------- #
#  teardown
# --------------------------------------------------------------------------- #
@remote_app.command()
def teardown(
    host: str = typer.Option(
        None, "--host", "-H", help="SSH connection. Uses saved default if omitted."
    ),
    project: str = typer.Option(None, "--project", help="Remote project directory"),
    key: str = typer.Option(None, "--key", "-k", help="Path to SSH private key"),
    port: int = typer.Option(22, "--port", "-p", help="SSH port"),
) -> None:
    """Tear down the remote sandbox and clean up containers."""
    conn = _resolve_host(host, key, port)
    if not conn:
        return

    remote_dir = project or provisioner.load_active_project()
    if not remote_dir:
        rc_error("No active remote project.", hint="Use --project or run sandbox first.")
        return

    console.print(f"\n  [bold]Remote teardown[/bold] — {conn.label}")
    rc_print(f"  Project: {remote_dir}\n", style="rc.dim")

    if not Confirm.ask("  Tear down the remote sandbox?", default=False):
        rc_print("  Cancelled.\n")
        return

    rc_print("  Tearing down...")
    r = provisioner.teardown_sandbox(conn, remote_dir)
    if r.ok:
        rc_success("Sandbox torn down")
        if r.stdout:
            for line in r.stdout.splitlines()[-5:]:
                rc_print(f"    {line}", style="rc.dim")
    else:
        rc_error(f"Teardown issue: {r.stderr or r.stdout}")

    console.print()
